# Generated by Django 6.0.3 on 2026-05-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_usuario_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_autorizacion', models.CharField(max_length=50)),
                ('fecha_autorizacion', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('negada', 'Negada'), ('vencida', 'Vencida')], default='aprobada', max_length=10)),
                ('servicios_autorizados', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autorización EPS',
                'verbose_name_plural': 'Autorizaciones EPS',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_rnos', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='canal_solicitud',
            field=models.CharField(choices=[('web', 'Página Web / App'), ('whatsapp', 'WhatsApp'), ('telefonica', 'Línea Telefónica'), ('presencial', 'Presencial')], default='web', max_length=15),
        ),
        migrations.AddField(
            model_name='cita',
            name='cuota_moderadora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='exento_cuota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('general', 'Medicina General'), ('especializada', 'Especializada'), ('prioritaria', 'Prioritaria')], default='general', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='regimen',
            field=models.CharField(blank=True, choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('pendiente_autorizacion', 'Pendiente de Autorización'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=25),
        ),
        migrations.AddField(
            model_name='cita',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.autorizacioneps'),
        ),
        migrations.AddField(
            model_name='autorizacioneps',
            name='eps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to='citas.eps'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliados', to='citas.eps'),
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('vigencia_dias', models.IntegerField(default=30)),
                ('estado', models.CharField(choices=[('pendiente_autorizacion', 'Pendiente de Autorización'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente_autorizacion', max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='citas.cita')),
                ('especialidad_solicitada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='citas.especialidad')),
                ('medico_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_medicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Médica',
                'verbose_name_plural': 'Órdenes Médicas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='autorizacioneps',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion', to='citas.ordenmedica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='orden_medica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.ordenmedica'),
        ),
    ]
