# Generated by Django 6.0.3 on 2026-05-14 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_autorizacioneps_eps_cita_canal_solicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('enfermedad_actual', models.TextField(blank=True)),
                ('antecedentes_personales', models.TextField(blank=True)),
                ('revision_sistemas', models.TextField(blank=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('saturacion_o2', models.IntegerField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico_principal', models.CharField(max_length=300)),
                ('codigo_cie10', models.CharField(blank=True, max_length=10)),
                ('tipo_diagnostico', models.CharField(choices=[('confirmado', 'Confirmado'), ('presuntivo', 'Presuntivo'), ('descartado', 'Descartado')], default='presuntivo', max_length=15)),
                ('conducta', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
        migrations.CreateModel(
            name='ItemReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('concentracion', models.CharField(blank=True, max_length=100)),
                ('forma_farmaceutica', models.CharField(blank=True, choices=[('tableta', 'Tableta'), ('capsula', 'Cápsula'), ('jarabe', 'Jarabe'), ('ampolla', 'Ampolla'), ('crema', 'Crema'), ('gotas', 'Gotas'), ('inhalador', 'Inhalador'), ('supositorio', 'Supositorio'), ('otro', 'Otro')], max_length=20)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('cantidad', models.CharField(blank=True, max_length=50)),
                ('indicaciones', models.TextField(blank=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='citas.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=200)),
                ('indicacion', models.CharField(blank=True, max_length=500)),
                ('urgente', models.BooleanField(default=False)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='citas.historiaclinica')),
            ],
        ),
    ]
